#include "helpers.h"
#include "MD.h"


machine_name_t machine_names[] PROGMEM = {
  { "GND---", 0},
  { "GND-SN", 1},
  { "GND-NS", 2},
  { "GND-IM", 3},
  { "TRX-BD", 16},
  { "TRX-SD", 17},
  { "TRX-XT", 18},
  { "TRX-CP", 19},
  { "TRX-RS", 20},
  { "TRX-RS", 21},
  { "TRX-CH", 22},
  { "TRX-OH", 23},
  { "TRX-CY", 24},
  { "TRX-MA", 25},
  { "TRX-CL", 26},
  { "TRX-XC", 27},
  { "TRX-B2", 28},
  { "EFM-BD", 32},
  { "EFM-SD", 33},
  { "EFM-XT", 34},
  { "EFM-CP", 35},
  { "EFM-RS", 36},
  { "EFM-CB", 37},
  { "EFM-HH", 38},
  { "EFM-CY", 39},
  { "E12-BD", 48},
  { "E12-SD", 49},
  { "E12-HT", 50},
  { "E12-LT", 51},
  { "E12-CP", 52},
  { "E12-RS", 53},
  { "E12-CB", 54},
  { "E12-CH", 55},
  { "E12-OH", 56},
  { "E12-RC", 57},
  { "E12-CC", 58},
  { "E12-BR", 59},
  { "E12-TA", 60},
  { "E12-TR", 61},
  { "E12-SH", 62},
  { "E12-BC", 63},
  { "P-I-BD", 64},
  { "P-I-SD", 65},
  { "P-I-MT", 66},
  { "P-I-ML", 67},
  { "P-I-MA", 68},
  { "P-I-RS", 69},
  { "P-I-RC", 70},
  { "P-I-CC", 71},
  { "P-I-HH", 72},
  { "INP-GA", 80},
  { "INP-GB", 81},
  { "INP-FA", 82},
  { "INP-FB", 83},
  { "INP-EA", 84},
  { "INP-EB", 85},
  { "MID-01", 96},
  { "MID-02", 97},
  { "MID-03", 98},
  { "MID-04", 99},
  { "MID-05", 100},
  { "MID-06", 101},
  { "MID-07", 102},
  { "MID-08", 103},
  { "MID-09", 104},
  { "MID-10", 105},
  { "MID-11", 106},
  { "MID-12", 107},
  { "MID-13", 108},
  { "MID-14", 109},
  { "MID-15", 110},
  { "MID-16", 111},
  { "CTR-AL", 112},
  { "CTR-8P", 113},
			
  { "CTR-RE", 120},
  { "CTR-GB", 121},
  { "CTR-EQ", 122},
  { "CTR-DX", 123},
			
  { "ROM-01", 128},
  { "ROM-02", 129},
  { "ROM-03", 130},
  { "ROM-04", 131},
  { "ROM-05", 132},
  { "ROM-06", 133},
  { "ROM-07", 134},
  { "ROM-08", 135},
  { "ROM-09", 136},
  { "ROM-10", 137},
  { "ROM-11", 138},
  { "ROM-12", 139},
  { "ROM-13", 140},
  { "ROM-14", 141},
  { "ROM-15", 142},
  { "ROM-16", 143},
  { "ROM-17", 144},
  { "ROM-18", 145},
  { "ROM-19", 146},
  { "ROM-20", 147},
  { "ROM-21", 148},
  { "ROM-22", 149},
  { "ROM-23", 150},
  { "ROM-24", 151},
  { "ROM-25", 152},
  { "ROM-26", 153},
  { "ROM-27", 154},
  { "ROM-28", 155},
  { "ROM-29", 156},
  { "ROM-30", 157},
  { "ROM-31", 158},
  { "ROM-32", 159},
  { "RAM-R1", 160},
  { "RAM-R2", 161},
  { "RAM-P1", 162},
  { "RAM-P2", 163},
			
  { "RAM-R3", 165},
  { "RAM-R4", 166},
  { "RAM-P3", 167},
  { "RAM-P4", 168},

  { "ROM-33", 176},
  { "ROM-34", 177},
  { "ROM-35", 178},
  { "ROM-36", 179},
  { "ROM-37", 180},
  { "ROM-38", 181},
  { "ROM-39", 182},
  { "ROM-40", 183},
  { "ROM-41", 184},
  { "ROM-42", 185},
  { "ROM-43", 186},
  { "ROM-44", 187},
  { "ROM-45", 188},
  { "ROM-46", 189},
  { "ROM-47", 190},
  { "ROM-48", 191}
};

PGM_P MDClass::getMachineName(uint8_t machine) {
  for (uint8_t i = 0; i < countof(machine_names); i++) {
    if (pgm_read_byte(&machine_names[i].id) == machine) {
      return machine_names[i].name;
    }
  }
  return NULL;
}

typedef struct model_param_name_s {
  char name[5];
  uint8_t id;
} model_param_name_t;

typedef struct model_to_param_names_s {
  uint8_t model;
  model_param_name_t *names;
} model_to_param_names_t;

model_param_name_t gnd_sn_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "RAMP", 2},
					    { "RDEC", 3} };
model_param_name_t gnd_ns_model_names[] = { { "DEC", 0} };
model_param_name_t gnd_im_model_names[] = { { "UP", 0},
					    { "UVAL", 1},
					    { "DOWN", 2},
					    { "DVAL", 3} };

model_param_name_t trx_bd_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "RAMP", 2},
					    { "RDEC", 3},
					    { "STRT", 4},
					    { "NOIS", 5},
					    { "HARM", 6},
					    { "CLIP", 7} };
model_param_name_t trx_b2_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "RAMP", 2},
					    { "HOLD", 3},
					    { "TICK", 4},
					    { "NOIS", 5},
					    { "DIRT", 6},
					    { "DIST", 7} };
model_param_name_t trx_sd_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "BUMP", 2},
					    { "BENV", 3},
					    { "SNAP", 4},
					    { "TONE", 5},
					    { "TUNE", 6},
					    { "CLIP", 7} };
model_param_name_t trx_xt_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "RAMP", 2},
					    { "RDEC", 3},
					    { "DAMP", 4},
					    { "DIST", 5},
					    { "DTYP", 6} };
model_param_name_t trx_cp_model_names[] = { { "CLPY", 0},
					    { "TONE", 1},
					    { "HARD", 2},
					    { "RICH", 3},
					    { "RATE", 4},
					    { "ROOM", 5},
					    { "RSIZ", 6},
					    { "RTUN", 7} };
model_param_name_t trx_rs_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "DIST", 2} };
model_param_name_t trx_cb_model_names[] = { { "PTCH", 0},
					    { "DEC", 2},
					    { "ENH", 3},
					    { "DAMP", 4},
					    { "TONE", 5},
					    { "BUMP", 6} };
model_param_name_t trx_ch_model_names[] = { { "GAP", 0},
					    { "DEC", 1},
					    { "HPF", 2},
					    { "LPF", 3},
					    { "MTAL", 4} };
model_param_name_t trx_oh_model_names[] = { { "GAP", 0},
					    { "DEC", 1},
					    { "HPF", 2},
					    { "LPF", 3},
					    { "MTAL", 4} };
model_param_name_t trx_cy_model_names[] = { { "RICH", 0},
					    { "DEC", 1},
					    { "TOP", 2},
					    { "TTUN", 3},
					    { "SIZE", 4},
					    { "PEAK", 5} };
model_param_name_t trx_ma_model_names[] = { { "ATT", 0},
					    { "SUS", 1},
					    { "REV", 2},
					    { "DAMP", 3},
					    { "RATL", 4},
					    { "RTYP", 5},
					    { "TONE", 6},
					    { "HARD", 7} };
model_param_name_t trx_cl_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "DUAL", 2},
					    { "ENH", 3},
					    { "TUNE", 4},
					    { "CLIC", 5} };
model_param_name_t trx_xc_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "RAMP", 2},
					    { "RDEC", 3},
					    { "DAMP", 4},
					    { "DIST", 5},
					    { "DTYP", 6} };

model_param_name_t efm_bd_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "RAMP", 2},
					    { "RDEC", 3},
					    { "MOD", 4},
					    { "MFRQ", 5},
					    { "MDEC", 6},
					    { "MFB", 7} };
model_param_name_t efm_sd_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "NOIS", 2},
					    { "NDEC", 3},
					    { "MOD", 4},
					    { "MFRQ", 5},
					    { "MDEC", 6},
					    { "HPF", 7} };
model_param_name_t efm_xt_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "RAMP", 2},
					    { "RDEC", 3},
					    { "MOD", 4},
					    { "MFRQ", 5},
					    { "MDEC", 6},
					    { "CLIC", 7} };
model_param_name_t efm_cp_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "CLPS", 2},
					    { "CDEC", 3},
					    { "MOD", 4},
					    { "MFRQ", 5},
					    { "MDEC", 6},
					    { "HPF", 7} };
model_param_name_t efm_rs_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "MOD", 2},
					    { "HPF", 3},
					    { "SNAR", 4},
					    { "SPTC", 5},
					    { "SDEC", 6},
					    { "SMOD", 7} };
model_param_name_t efm_cb_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "SNAP", 2},
					    { "FB", 3},
					    { "MOD", 4},
					    { "MFRQ", 5},
					    { "MDEC", 6} };
model_param_name_t efm_hh_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "TREM", 2},
					    { "TFRQ", 3},
					    { "MOD", 4},
					    { "MFRQ", 5},
					    { "MDEC", 6},
					    { "FB", 7} };
model_param_name_t efm_cy_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "FB", 2},
					    { "HPF", 3},
					    { "MOD", 4},
					    { "MFRQ", 5},
					    { "MDEC", 6} };

model_param_name_t e12_bd_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "SNAP", 2},
					    { "SPLN", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_sd_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "RING", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_ht_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "HPQ", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_lt_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "RING", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_cp_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "HPQ", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_rs_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "RRTL", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_cb_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "HPQ", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_ch_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "HPQ", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_oh_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "STOP", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_rc_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "BELL", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_cc_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "HPQ", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_br_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "REAL", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_ta_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "HPQ", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_tr_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "HPQ", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_sh_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "SLEW", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };
model_param_name_t e12_bc_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HP", 2},
					    { "BC", 3},
					    { "STRT", 4},
					    { "RTRG", 5},
					    { "RTIM", 6},
					    { "BEND", 7} };

model_param_name_t p_i_bd_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HARD", 2},
					    { "HAMR", 3},
					    { "TENS", 4},
					    { "DAMP", 5} };
model_param_name_t p_i_sd_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HARD", 2},
					    { "TENS", 3},
					    { "RVOL", 4},
					    { "RDEC", 5},
					    { "RING", 6} };
model_param_name_t p_i_mt_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HARD", 2},
					    { "HAMR", 3},
					    { "TUNE", 4},
					    { "DAMP", 5},
					    { "SIZE", 6},
					    { "POS", 7} };
model_param_name_t p_i_ml_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HARD", 2},
					    { "TENS", 3} };
model_param_name_t p_i_ma_model_names[] = { { "GRNS", 0},
					    { "DEC", 1},
					    { "GLEN", 2},
					    { "SIZE", 4},
					    { "HARD", 5} };
model_param_name_t p_i_rs_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HARD", 2},
					    { "RING", 3},
					    { "RVOL", 4},
					    { "RDEC", 5} };
model_param_name_t p_i_rc_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HARD", 2},
					    { "RING", 3},
					    { "AG", 4},
					    { "AU", 5},
					    { "BR", 6},
					    { "GRAB", 7} };
model_param_name_t p_i_cc_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "HARD", 2},
					    { "RING", 3},
					    { "AG", 4},
					    { "AU", 5},
					    { "BR", 6},
					    { "GRAB", 7} };
model_param_name_t p_i_hh_model_names[] = { { "PTCH", 0},
					    { "DEC", 1},
					    { "CLSN", 2},
					    { "RING", 3},
					    { "AG", 4},
					    { "AU", 5},
					    { "BR", 6},
					    { "CLOS", 7} };

model_param_name_t inp_ga_model_names[] = { { "VOL", 0},
					    { "GATE", 1},
					    { "ATCK", 2},
					    { "HLD", 3},
					    { "DEC", 4} };
model_param_name_t inp_fa_model_names[] = { { "ALEV", 0},
					    { "GATE", 1},
					    { "FATK", 2},
					    { "FHLD", 3},
					    { "FDEC", 4},
					    { "FDPH", 5},
					    { "FFRQ", 6},
					    { "FQ", 7} };
model_param_name_t inp_ea_model_names[] = { { "AVOL", 0},
					    { "AHLD", 1},
					    { "ADEC", 2},
					    { "FQ", 3},
					    { "FDPH", 4},
					    { "FHLD", 5},
					    { "FDEC", 6},
					    { "FFRQ", 7} };

model_param_name_t mid_model_names[] = { { "NOTE", 0},
					 { "N2", 1},
					 { "N3", 2},
					 { "LEN", 3},
					 { "VEL", 4},
					 { "PB", 5},
					 { "MW", 6},
					 { "AT", 7},
					 { "CC1D", 8},
					 { "CC1V", 9},
					 { "CC2D", 10},
					 { "CC2V", 11},
					 { "CC3D", 12},
					 { "CC3V", 13},
					 { "CC4D", 14},
					 { "CC4V", 15},
					 { "CC5D", 16},
					 { "CC5V", 17},
					 { "CC6D", 18},
					 { "CC6V", 19},
					 { "PCHG", 20},
					 { "LFOS", 21},
					 { "LFOD", 22},
					 { "LFOM", 23} };

model_param_name_t ctr_al_model_names[] = { { "SYN1", 0},
					    { "SYN2", 1},
					    { "SYN3", 2},
					    { "SYN4", 3},
					    { "SYN5", 4},
					    { "SYN6", 5},
					    { "SYN7", 6},
					    { "SYN8", 7} };
model_param_name_t ctr_8p_model_names[] = { { "P1", 0},
					    { "P2", 1},
					    { "P3", 2},
					    { "P4", 3}, 
					    { "P5", 4},
					    { "P6", 5},
					    { "P7", 6},
					    { "P8", 7},
					    { "P1T", 8},
					    { "P1P", 9},
					    { "P2T", 10},
					    { "P2P", 11},
					    { "P3T", 12},
					    { "P3P", 13},
					    { "P4T", 14},
					    { "P4P", 15},
					    { "P5T", 16},
					    { "P5P", 17},
					    { "P6T", 18},
					    { "P6P", 19},
					    { "P7T", 20},
					    { "P7P", 21},
					    { "P8T", 22},
					    { "P8P", 23} };
model_param_name_t rom_model_names[] = { { "PTCH", 0},
					 { "DEC", 1},
					 { "HOLD", 2},
					 { "BRR", 3},
					 { "STRT", 4},
					 { "END", 5},
					 { "RTRG", 6},
					 { "RTIM", 7} };
model_param_name_t ram_r_model_names[] = { { "MLEV", 0},
					   { "MBAL", 1},
					   { "ILEV", 2},
					   { "IBAL", 3},
					   { "CUE1", 4},
					   { "CUE2", 5},
					   { "LEN", 6},
					   { "RATE", 7} };

model_to_param_names_t model_param_names[] = {
  { GND_SN_MODEL, gnd_sn_model_names },
  { GND_NS_MODEL, gnd_ns_model_names },
  { GND_IM_MODEL, gnd_im_model_names },
  
  { TRX_BD_MODEL, trx_bd_model_names },
  { TRX_B2_MODEL, trx_b2_model_names },
  { TRX_SD_MODEL, trx_sd_model_names },
  { TRX_XT_MODEL, trx_xt_model_names },
  { TRX_CP_MODEL, trx_cp_model_names },
  { TRX_RS_MODEL, trx_rs_model_names },
  { TRX_CH_MODEL, trx_ch_model_names },
  { TRX_OH_MODEL, trx_oh_model_names },
  { TRX_CY_MODEL, trx_cy_model_names },
  { TRX_MA_MODEL, trx_ma_model_names },
  { TRX_CL_MODEL, trx_cl_model_names },
  { TRX_XC_MODEL, trx_xc_model_names },

  { EFM_BD_MODEL, efm_bd_model_names },
  { EFM_SD_MODEL, efm_sd_model_names },
  { EFM_XT_MODEL, efm_xt_model_names },
  { EFM_CP_MODEL, efm_cp_model_names },
  { EFM_RS_MODEL, efm_rs_model_names },
  { EFM_CB_MODEL, efm_cb_model_names },
  { EFM_HH_MODEL, efm_hh_model_names },
  { EFM_CY_MODEL, efm_cy_model_names },

  { E12_BD_MODEL, e12_bd_model_names },
  { E12_SD_MODEL, e12_sd_model_names },
  { E12_HT_MODEL, e12_ht_model_names },
  { E12_LT_MODEL, e12_lt_model_names },
  { E12_CP_MODEL, e12_cp_model_names },
  { E12_RS_MODEL, e12_rs_model_names },
  { E12_CB_MODEL, e12_cb_model_names },
  { E12_CH_MODEL, e12_ch_model_names },
  { E12_OH_MODEL, e12_oh_model_names },
  { E12_RC_MODEL, e12_rc_model_names },
  { E12_CC_MODEL, e12_cc_model_names },
  { E12_BR_MODEL, e12_br_model_names },
  { E12_TA_MODEL, e12_ta_model_names },
  { E12_TR_MODEL, e12_tr_model_names },
  { E12_SH_MODEL, e12_sh_model_names },
  { E12_BC_MODEL, e12_bc_model_names },

  { P_I_BD_MODEL, p_i_bd_model_names },
  { P_I_SD_MODEL, p_i_sd_model_names },
  { P_I_MT_MODEL, p_i_mt_model_names },
  { P_I_ML_MODEL, p_i_ml_model_names },
  { P_I_MA_MODEL, p_i_ma_model_names },
  { P_I_RS_MODEL, p_i_rs_model_names },
  { P_I_RC_MODEL, p_i_rc_model_names },
  { P_I_CC_MODEL, p_i_cc_model_names },
  { P_I_HH_MODEL, p_i_hh_model_names },

  { INP_GA_MODEL, inp_ga_model_names },
  { INP_FA_MODEL, inp_fa_model_names },
  { INP_EA_MODEL, inp_ea_model_names },

  { INP_GB_MODEL, inp_ga_model_names },
  { INP_FB_MODEL, inp_fa_model_names },
  { INP_EB_MODEL, inp_ea_model_names },

  { MID_MODEL,    mid_model_names },

  { CTR_AL_MODEL, ctr_al_model_names },
  { CTR_8P_MODEL, ctr_8p_model_names },
  { ROM_MODEL,    rom_model_names },
  { RAM_R1_MODEL,  ram_r_model_names },
  { RAM_R2_MODEL,  ram_r_model_names },
  { RAM_R3_MODEL,  ram_r_model_names },
  { RAM_R4_MODEL,  ram_r_model_names }
};
  
