MIDICTRL_LIBS = GUI MidiTools

include ../../../makefiles/Host.mk

all: midi-send

midi-send: MidiSend.host.o logging.host.o HexFile.host.o MidiFirmwareSender.host.o $(OBJS)
	$(CXX) $(CLDFLAGS) -o $@ $+ $(LIBS)

clean:
	- rm -f *.o midi-send midi-merge midi-console
